title: Life Array
email: hello@lifearray.uk
description: >- # this means to ignore newlines until "baseurl:"
  description goes here
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lifearray.uk" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock